### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by mcoret** [itzmeanjan/ascon#21]
Hello!

Thank you for your excellent work. I've found this library to perform well and quickly under Linux. Oddly enough, when compiling the library under Windows (using both mingw64 and Visual Studio), it doesn't yield the correct KAT tests. I've examined the code but am unsure why it behaves so differently between Linux and Windows.
Interestingly, when compiled under Windows using MSYS, it functions correctly, much like on Linux, which is what I had expected.

Thank you once again!

**Comment by itzmeanjan** [comment]
Hi @mcoret, thanks for reporting this. I've not ever tested the library on Windows and I don't have access to such infrastructures so it might be little bit tricky for me to resolve the issue.
